### ISSUE TITLE
deployed to heroku but not work

### ISSUE THREAD

**Issue by branchmaster** [atalaydenknalbant/autosubscriber-youtube#2]
hi atalay , 
I'm try to deploy using your button , deployed succed but not work.
waiting for your response
finest regards

**Comment by atalaydenknalbant** [comment]
it's not a web-based app these are just plain python codes no GUI that's why. You have to use your own python to run Type_1_Websites.py, Type_2_Websites.py, ytbpals.py, ytmonster.py, goviral.py files.

**Comment by branchmaster** [comment]
i know that , but all your need heroku buildpacks are exist like selenium , chrome headless & ...
& heroku not able only launch web apps , see procfile docs for made background process don't be sleep on elastic hards.
waiting for your response
finest regards

**Comment by atalaydenknalbant** [comment]
Ok I will try to implement your advice to my codes and deploy an operating Heroku app.

**Comment by branchmaster** [comment]
thanks fir your changes , 
please make app.json file too in root of master brunch for make expertise deploy items like set buildpacks needed like selenium , chrome headless for runtime .

**Comment by atalaydenknalbant** [comment]
Now I can run this app from Heroku CLI but you still need to find a way to edit config.ini to match with your own accounts.
