### ISSUE TITLE
Pc formated

### ISSUE THREAD

**Issue by leothewolf122** [atalaydenknalbant/autosubscriber-youtube#23]
![image](https://user-images.githubusercontent.com/91257665/152503631-c269f7c5-a05d-4f32-8c13-ece71857dea2.png)

I am facing this issue can you pls tell me what went wrong I used this program yesterday and it worked fine but today had to format it and it aint working

**Comment by atalaydenknalbant** [comment]
I was facing same problem today so looks like chrome needs an update also install webdriver with same version with newest chrome. Lastly, make sure change user agent that matches with latest chrome.

**Comment by leothewolf122** [comment]
Ok for sure let me do all the specifics you mentioned!!

**Comment by atalaydenknalbant** [comment]
i probably need to add captcha solver eventually, since google makes it harder to login for older chrome versions.

**Comment by leothewolf122** [comment]
Umm yea but man that program is awsm....I made like bots for a chatting site but this is another level!!

**Comment by leothewolf122** [comment]
![image](https://user-images.githubusercontent.com/91257665/152506039-438819c1-e267-4f11-b7b9-749e7574fb23.png)
![image](https://user-images.githubusercontent.com/91257665/152506085-da344131-6295-45b9-adbc-9428de4e2172.png)
Well ig as you can see current version of chrome is 81 while we have driver for 80 so this might be causing prblm

**Comment by leothewolf122** [comment]
Ok so I tried with older version of chrome(80) still aint working....working for you?

**Comment by atalaydenknalbant** [comment]
use latest chrome and webdriver also update your config file to match with your newest chrome.

**Comment by atalaydenknalbant** [comment]
update user agent line in your config file.

**Comment by leothewolf122** [comment]
I did all that but with newer version it aint working

**Comment by atalaydenknalbant** [comment]
login to your google account in normal and incognito mode in newest versions before running script.

**Comment by atalaydenknalbant** [comment]
if it still fails send me g_screenshot.png

**Comment by leothewolf122** [comment]
Ok for sure let me do so!!

**Comment by leothewolf122** [comment]
Bro the error seems this

: TypeErrorTypeErrorexpected str, bytes or os.PathLike object, not NoneType: : 
expected str, bytes or os.PathLike object, not NoneTypeexpected str, bytes or os.PathLike object, not NoneType

**Comment by leothewolf122** [comment]
And inside screenshot folder theres only .keep file

**Comment by atalaydenknalbant** [comment]
this is about filepath error make sure your chromedriver in your path environment

**Comment by leothewolf122** [comment]
Ohh wait I forgot that step....so sorry man

**Comment by leothewolf122** [comment]
Oops its started working....sorry man...btw is there any way to automate this step of running every 12hrs? Like am thinking to upload on linux server....

I am not versed with heroku can it give the same functionality I want?

**Comment by atalaydenknalbant** [comment]
heroku is not working. I never tried linux. You can try windows task scheduler

**Comment by leothewolf122** [comment]
Ohh ok well no worries ill try something if those work ill let you know....thanks for all the help!!

**Comment by leothewolf122** [comment]
Thanks from all the peeps who are benefiting from this repo and thanks for keeping it open source
