### ISSUE TITLE
please changes commits on read variables location

### ISSUE THREAD

**Issue by branchmaster** [atalaydenknalbant/autosubscriber-youtube#3]
hi atalay ,
please change where to read variables location from config.ini to public heroku vars can be found in your web-based heroku panel , click on your dyno , click setting tab scroll to 'Config Vars' & click on reveal config vars button . here you can set public vars like all the things in config.ini & heroku read from here . you can also set config vars in heroku deploy button to free on input manually after deploy.
you must changes all the codes like bellow :
config_object.read("config.ini")
i found it on GoViral.py file & you know what files include this .
waiting for your commited :)
finest regards

**Comment by atalaydenknalbant** [comment]
I did what you told me but google won't allow any logins from heroku with or without user agent.

**Comment by branchmaster** [comment]
you can set proxy for kick ass google on your road map :)
