### ISSUE TITLE
Doesn't Seem to Work.

### ISSUE THREAD

**Issue by lsvcode** [atalaydenknalbant/autosubscriber-youtube#34]
Google removed the "Less Secure Apps" function, so therefore when I deployed to Heroku and turned on some of the dyno workers, it does not seem to be functioning at all. Please is there a work around or something I can do to get it working as it seems like very good  and helpful software if it does.

Thanks.

**Comment by atalaydenknalbant** [comment]
Run in your local computer and follow instructions. I don't know any other way to login google accounts.
