### ISSUE TITLE
password manager disabling

### ISSUE THREAD

**Issue by tonykor** [atalaydenknalbant/autosubscriber-youtube#35]
Users keep in mind that this script disable chrome password manager!
Delevoper, please inform users about this so they can save their password!

**Comment by atalaydenknalbant** [comment]
Users need to use config.ini to enter their passwords and other credentials this script never uses autofills.

**Comment by tonykor** [comment]
it clears chrome cache

```
    driver.get('chrome://settings/clearBrowserData')
    wait = WebDriverWait(driver, timeout)
    wait.until(get_clear_browsing_button)
    get_clear_browsing_button(driver).click()
    wait.until_not(get_clear_browsing_button)
```

and disables password manager

```
else:
        chrome_options.add_argument("--disable-extensions")
        prefs = {"profile.managed_default_content_settings.images": 2,
                 "disk-cache-size": 4096,
                 "profile.password_manager_enabled": False,
                 "credentials_enable_service": False}
```

after using this script my chrome browser reset all passwords and did not remember new passwords

**Comment by atalaydenknalbant** [comment]
This script won't be using ur regular chrome it uses chromedriver.

**Comment by atalaydenknalbant** [comment]
it start with an empty chrome browser that's why you won't see your saved passwords or autofills.

**Comment by tonykor** [comment]
can it use the same chromedriver that my chrome is using? I do not see my saved passwords in running script, but i don't see them in my regular chrome as well. I think that script by default using the same driver as regular chrome so it changes it's config. I do not specify any special path to chromedriver anywhere.

**Comment by atalaydenknalbant** [comment]
No, it will not. You need to enter our passwords and info into config.ini file

**Comment by tonykor** [comment]
sure i enter them in config.ini, but my desktop chrome is not saving passwords anymore after running this script, so i think that this script manipulate the same chrome driver that using regular desktop chrome application, at least on my ubuntu

**Comment by atalaydenknalbant** [comment]
it won't manipulate on windows not sure about ubuntu
