### ISSUE TITLE
Launch question

### ISSUE THREAD

**Issue by GODIMONGO** [atalaydenknalbant/autosubscriber-youtube#37]
Здравствуйте можете подсказать как использовать данный софт

Hello can you tell me how to use this software

**Comment by GODIMONGO** [comment]
You could also add support for clifl.com?

**Comment by atalaydenknalbant** [comment]
read usage in readme. Try to run any .py folder in main folder except setup. You need to fill config.ini to use the given websites.

**Comment by atalaydenknalbant** [comment]
I will add  clifl and view2b 2.0 version

**Comment by GODIMONGO** [comment]
If it is more convenient for you, I can finish my library for clifl.com (yt_monster_py)

**Comment by atalaydenknalbant** [comment]
i will release 2.0.0 today. Which will include ytmonsterru(clifl) and view2be. But ytmonsterru causes some problems thats why i also added undetected_chromedriver but i think it still can't pass extra cloudflare security which is exist in ytmonsterru

**Comment by GODIMONGO** [comment]
I suggest then using the api

**Comment by GODIMONGO** [comment]
I'm not very good at working with the browser, but I can help to get a link to the task and confirm the execution

**Comment by atalaydenknalbant** [comment]
Everything else included as code in 2.0 version and works perfectly fine.

**Comment by GODIMONGO** [comment]
it would be great if you added support for VK conditionally via api https://ytmonster.ru/api/v2/ there is also a mini client that would also be useful https://uppe.ru/viewer/

**Comment by GODIMONGO** [comment]
![image](https://github.com/atalaydenknalbant/autosubscriber-youtube/assets/106483765/22b38030-ccd7-4bfd-af27-c80318002ec3)

**Comment by atalaydenknalbant** [comment]
program runs on https://uppe.ru/viewer/ for watching videos

**Comment by atalaydenknalbant** [comment]
but can't pass cloudflare since even undetected_chromedriver still be detected by cloudflare anti-bot service

**Comment by GODIMONGO** [comment]
Sad =(
