### ISSUE TITLE
ytmonsterru err

### ISSUE THREAD

**Issue by GODIMONGO** [atalaydenknalbant/autosubscriber-youtube#38]
log: https://hastebin.com/share/vimasohiga.typescript
Does not work ytmonsterru installed the required libraries from requriments

**Comment by GODIMONGO** [comment]
ytmonster.net opens all windows not hidden but on the full screen, which interferes with work

**Comment by GODIMONGO** [comment]
err: https://hastebin.com/share/wiruyexume.lua
on Pterodactyl the program does not work and on my pc it is very stressful on my system

**Comment by GODIMONGO** [comment]
I'll try it later on windows server

**Comment by atalaydenknalbant** [comment]
For the first error seems like you can't login to your google account. For ytmonster.net to work it needs to be open in not headless otherwise ytmonster.net website doesn't count the views and stuck on video loading. You can see progress on https://www.ytmonster.net/exchange/views while running the code.(If it stucks loading video it means you need to start over)

**Comment by atalaydenknalbant** [comment]
for your first problem, add this to line 211 driver.save_screenshot("screenshots/screenshot.png") and send me the screenshot

**Comment by GODIMONGO** [comment]
![изображение](https://github.com/atalaydenknalbant/autosubscriber-youtube/assets/106483765/68d63538-13eb-476f-aac3-42b93c47435a)
![screenshot](https://github.com/atalaydenknalbant/autosubscriber-youtube/assets/106483765/088d0c49-3044-46da-9ce9-d4c24e46d7c9)

**Comment by GODIMONGO** [comment]
Found the problem. The browser is not secure. 
![screenshot4](https://github.com/atalaydenknalbant/autosubscriber-youtube/assets/106483765/beb85075-0507-44ad-93d5-2e8485b8d363)

**Comment by atalaydenknalbant** [comment]
create new account with almost no security no ffa that might fix it.

**Comment by GODIMONGO** [comment]
I don't really understand there's no extra security.

**Comment by atalaydenknalbant** [comment]
old accounts cause this problem there is no way to solve this problem unless you prelogged to your account before starting script, which i will add in next update to my script.

**Comment by atalaydenknalbant** [comment]
I updated version to 2.05 now you only need a pre-logged account  to run scripts.

**Comment by GODIMONGO** [comment]
Thanks, I'll try it now

**Comment by atalaydenknalbant** [comment]
bypassing ytmonsterru cloudflare security is beyond my skills i am still waiting for undetected_chromedriver update that bypass that security.

**Comment by GODIMONGO** [comment]
And you can make that the browser installed the extension and clicked in it to launch video in ytmonsterru in case the client crashed, the browser re-launched it and preferably that would still be possible to use the extension for vpn simply they have the ability to view video through the client ytmonster but for each new client more than 3 need a new IP I would be grateful if you would do it as my project for scoring free can not withstand a large load of users

Translated with www.DeepL.com/Translator (free version)

**Comment by GODIMONGO** [comment]
> bypassing ytmonsterru cloudflare security is beyond my skills i am still waiting for undetected_chromedriver update that bypass that security.

I'll be waiting
