### ISSUE TITLE
how to Run?

### ISSUE THREAD

**Issue by AxamGaming** [atalaydenknalbant/autosubscriber-youtube#39]
im having trouble trying to run the programe..
How to run it? and where do i run it?
pls answer.

**Comment by atalaydenknalbant** [comment]
first you need to edit config.ini file with your credentials then you can run .py files for each website 1 by 1. Some websites are inactive you find find them in readme section.

**Comment by AxamGaming** [comment]
> first you need to edit config.ini file with your credentials then you can run .py files for each website 1 by 1. Some websites are inactive you find find them in readme section.

thanks but i get this -

Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\autosubscriber-youtube-master\ytbpals.py", line 1, in <module>
    from selenium_codes import sub4sub_websites_selenium as sws
  File "C:\Users\Dell\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by atalaydenknalbant** [comment]
you need to install selenium with pip

**Comment by AxamGaming** [comment]
thanks a lot man

**Comment by AxamGaming** [comment]
bro it asks me to add 
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

i have installed all the requirements fromthe requirements text

**Comment by atalaydenknalbant** [comment]
looks like chromedriver you are using old one and not compatible with current chrome version. You can either delete chromedriver in you path in system environments or You can download 121 chromedriver version https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.85/win64/chrome-win64.zip.             then replace chromedriver.exe inside your      C:\Chromedriver\       location

**Comment by AxamGaming** [comment]
oh i could not find a ssuitable driver the latest one was 181

**Comment by atalaydenknalbant** [comment]
selenium handles the chromedriver installation you just need to delete chromedriver path from your system environments

**Comment by atalaydenknalbant** [comment]
sorry i gave you incorrect link here is the link for chromedriver: https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.85/win64/chromedriver-win64.zip

**Comment by AxamGaming** [comment]
i get 

Running Local Version

DevTools listening on ws://127.0.0.1:65015/devtools/browser/d4ac7615-0eed-4445-b7bf-8a409685f4e5
[7300:10248:0216/231438.029:ERROR:gl_display.cc(520)] EGL Driver message (Error) eglCreateContext: Requested GLES version (3.0) is greater than max supported (2, 0).
[7300:10248:0216/231443.953:ERROR:gl_display.cc(520)] EGL Driver message (Error) eglCreateContext: Requested GLES version (3.0) is greater than max supported (2, 0).
Traceback (most recent call last):
  File "C:\Users\Vihas Punsilu\Desktop\autosubscriber-youtube-master\ytbpals.py", line 43, in <module>
    sws.ytbpals_functions(required_dict)
  File "C:\Users\Vihas Punsilu\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 891, in ytbpals_functions
    driver.find_element(By.ID, 'email').send_keys(req_dict['email_ytbpals'])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="email"]"}
  (Session info: chrome=121.0.6167.185); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF7C84A5E42+3538674]
        (No symbol) [0x00007FF7C80C4C02]
        (No symbol) [0x00007FF7C7F75AEB]
        (No symbol) [0x00007FF7C7FBBF4E]
        (No symbol) [0x00007FF7C7FBC0CC]
        (No symbol) [0x00007FF7C7FFE477]
        (No symbol) [0x00007FF7C7FDF0EF]
        (No symbol) [0x00007FF7C7FFBDE3]
        (No symbol) [0x00007FF7C7FDEE53]
        (No symbol) [0x00007FF7C7FAF514]
        (No symbol) [0x00007FF7C7FB0631]
        GetHandleVerifier [0x00007FF7C84D6CAD+3738973]
        GetHandleVerifier [0x00007FF7C852C506+4089270]
        GetHandleVerifier [0x00007FF7C8524823+4057299]
        GetHandleVerifier [0x00007FF7C81F5C49+720121]
        (No symbol) [0x00007FF7C80D126F]
        (No symbol) [0x00007FF7C80CC304]
        (No symbol) [0x00007FF7C80CC432]
        (No symbol) [0x00007FF7C80BBD04]
        BaseThreadInitThunk [0x00007FF86AA07344+20]
        RtlUserThreadStart [0x00007FF86B4426B1+33]

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


 then closes

**Comment by atalaydenknalbant** [comment]
it looks like ytbpals is not working apparently i will fix it asap and release new version of autosubscriber. For me youlikehits and type2_websites working without any error.

**Comment by AxamGaming** [comment]
wait before i get any of this messages it worked and did 2 tasks then got errors
s

**Comment by atalaydenknalbant** [comment]
Released 2.2 check any errors if there any. Also you can only run some websites while you are not using chrome but some functions like:  youlikehits.py it doesn't require that kind of google login so you can use chrome freely during that run.
